server:
  port: 9002

spring:
  application:
    name: cloud-consumers

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
