server:
  port: 8090

spring:
  application:
    name: cloud-gateway8090
  cloud:
    gateway:
      routes:
       -  id: cloud-consumers
          uri: http://localhost:9002
          predicates:
            - Path= /consumers/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000